{"Functions": {"ArithmeticException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message."]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ArithmeticException with the specified detail message.", "history": "Added in API level 1", "FullName": "public ArithmeticException (String s)"}, "ArithmeticException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ArithmeticException with no detail message.", "history": "Added in API level 1", "FullName": "public ArithmeticException ()"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#lang#RuntimeException_E@"], "ClassName": "java.lang.ArithmeticException", "ClassDesc": "Thrown when an exceptional arithmetic condition has occurred. For example, an integer \"divide by zero\" throws an instance of this class. ArithmeticException objects may be constructed by the virtual machine as if"}