{"Functions": {"Error()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new error with null as its detail message. The cause is not initialized, and may subsequently be initialized by a call to @B_java#lang#Throwable#initCause_E@.", "history": "Added in API level 1", "FullName": "public Error ()"}, "Error(java.lang.String,java.lang.Throwable,boolean,boolean)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message."], ["@B_java#lang#Throwable_E@", "Throwable: the cause. (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"], ["boolean", "boolean: whether or not suppression is enabled or disabled"], ["boolean", "boolean: whether or not the stack trace should be writable"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new error with the specified detail message, cause, suppression enabled or disabled, and writable stack trace enabled or disabled.", "history": "Added in API level 24", "FullName": "protected Error (String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)"}, "Error(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message. The detail message is saved for later retrieval by the @B_java#lang#Throwable#getMessage_E@ method."]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new error with the specified detail message. The cause is not initialized, and may subsequently be initialized by a call to @B_java#lang#Throwable#initCause_E@.", "history": "Added in API level 1", "FullName": "public Error (String message)"}, "Error(java.lang.String, java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message (which is saved for later retrieval by the @B_java#lang#Throwable#getMessage_E@ method)."], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new error with the specified detail message and cause. Note that the detail message associated with cause is", "history": "added in API level 1", "FullName": "public Error (String message, Throwable cause)"}, "Error(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new error with the specified cause and a detail message of (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause). This constructor is useful for errors that are little more than wrappers for other throwables.", "history": "Added in API level 1", "FullName": "public Error (Throwable cause)"}, "Error(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message (which is saved for later retrieval by the @B_java#lang#Throwable#getMessage_E@ method)."], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method). (A null value is permitted, and indicates that the cause is nonexistent or unknown.)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new error with the specified detail message and cause. Note that the detail message associated with cause is", "history": "Added in API level 1", "FullName": "public Error (String message, Throwable cause)"}}, "Inheritance": ["@B_java#lang#Throwable_E@"], "ClassName": "java.lang.Error", "ClassDesc": "An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions. The ThreadDeath error, though a \"normal\" condition, is also a subclass of Error because most applications should not try to catch it. A method is not required to declare in its throws clause any subclasses of Error that might be thrown during the execution of the method but not caught, since these errors are abnormal conditions that should never occur. That is, Error and its subclasses are regarded as unchecked exceptions for the purposes of compile-time checking of exceptions."}