{"Functions": {"DirectoryIteratorException(java.io.IOException)": {"Returns": [], "Parameters": [["@B_java#io#IOException_E@", "IOException: the IOException that caused the directory iteration to fail"]], "Throws": [["@B_java#lang#NullPointerException_E@", "if the cause is null"]], "SeeAlso": [], "Permissions": [], "Description": "Constructs an instance of this class.", "history": "Added in API level 26", "FullName": "public DirectoryIteratorException (IOException cause)"}, "getCause()": {"Returns": [["@B_java#io#IOException_E@", "the cause"]], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Returns the cause of this exception.", "history": "Added in API level 26", "FullName": "public IOException getCause ()"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#lang#RuntimeException_E@", "@B_java#util#ConcurrentModificationException_E@"], "ClassName": "java.nio.file.DirectoryIteratorException", "ClassDesc": "Runtime exception thrown if an I/O error is encountered when iterating over the entries in a directory. The I/O error is retrieved as an @B_java#io#IOException_E@ using the @B_java#nio#file#DirectoryIteratorException#getCause_E@ method."}