{"Functions": {"ExecutionException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ExecutionException with the specified detail message. The cause is not initialized, and may subsequently be initialized by a call to @B_java#lang#Throwable#initCause_E@.", "history": "Added in API level 1", "FullName": "protected ExecutionException (String message)"}, "ExecutionException(java.lang.String,java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"], ["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ExecutionException with the specified detail message and cause.", "history": "Added in API level 1", "FullName": "public ExecutionException (String message, Throwable cause)"}, "ExecutionException(java.lang.Throwable)": {"Returns": [], "Parameters": [["@B_java#lang#Throwable_E@", "Throwable: the cause (which is saved for later retrieval by the @B_java#lang#Throwable#getCause_E@ method)"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ExecutionException with the specified cause. The detail message is set to (cause == null ? null : cause.toString()) (which typically contains the class and detail message of cause).", "history": "Added in API level 1", "FullName": "public ExecutionException (Throwable cause)"}, "ExecutionException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs an ExecutionException with no detail message. The cause is not initialized, and may subsequently be initialized by a call to @B_java#lang#Throwable#initCause_E@.", "history": "Added in API level 1", "FullName": "protected ExecutionException ()"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@"], "ClassName": "java.util.concurrent.ExecutionException", "ClassDesc": "Exception thrown when attempting to retrieve the result of a task that aborted by throwing an exception. This exception can be inspected using the @B_java#lang#Throwable#getCause_E@ method."}