{"Functions": {"ConnectException()": {"Returns": [], "Parameters": [], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Construct a new ConnectException with no detailed message.", "history": "Added in API level 1", "FullName": "public ConnectException ()"}, "ConnectException(java.lang.String)": {"Returns": [], "Parameters": [["@B_java#lang#String_E@", "String: the detail message"]], "Throws": [], "SeeAlso": [], "Permissions": [], "Description": "Constructs a new ConnectException with the specified detail message as to why the connect error occurred. A detail message is a String that gives a specific description of this error.", "history": "Added in API level 1", "FullName": "public ConnectException (String msg)"}}, "Inheritance": ["@B_java#lang#Throwable_E@", "@B_java#lang#Exception_E@", "@B_java#io#IOException_E@", "@B_java#net#SocketException_E@"], "ClassName": "java.net.ConnectException", "ClassDesc": "Signals that an error occurred while attempting to connect a socket to a remote address and port. Typically, the connection was refused remotely (e.g., no process is listening on the remote address/port)."}